import { Image } from "@/types";

export const images: Image[] = [
  {
    id: "0",
    folder: "dining",
    filename: "DSC_5845.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "1",
    folder: "dining",
    filename: "DSC_5993.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "2",
    folder: "dining",
    filename: "DSC_6578.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "3",
    folder: "dining",
    filename: "DSC_6875.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "4",
    folder: "dining",
    filename: "DSC_7251.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "5",
    folder: "dining",
    filename: "DSC_5858.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "6",
    folder: "dining",
    filename: "DSC_5995.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "7",
    folder: "dining",
    filename: "DSC_6584.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "8",
    folder: "dining",
    filename: "DSC_6876.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "9",
    folder: "dining",
    filename: "DSC_7255.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "10",
    folder: "dining",
    filename: "DSC_5866.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "11",
    folder: "dining",
    filename: "DSC_5996.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "12",
    folder: "dining",
    filename: "DSC_6589.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "13",
    folder: "dining",
    filename: "DSC_6880.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "14",
    folder: "dining",
    filename: "DSC_7258.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "15",
    folder: "dining",
    filename: "DSC_5879.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "16",
    folder: "dining",
    filename: "DSC_5997.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "17",
    folder: "dining",
    filename: "DSC_6602.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "18",
    folder: "dining",
    filename: "DSC_6882.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "19",
    folder: "dining",
    filename: "DSC_7259.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "20",
    folder: "dining",
    filename: "DSC_5893.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "21",
    folder: "dining",
    filename: "DSC_5999.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "22",
    folder: "dining",
    filename: "DSC_6610.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "23",
    folder: "dining",
    filename: "DSC_6884.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "24",
    folder: "dining",
    filename: "DSC_7260.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "25",
    folder: "dining",
    filename: "DSC_5894.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "26",
    folder: "dining",
    filename: "DSC_6045.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "27",
    folder: "dining",
    filename: "DSC_6620.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "28",
    folder: "dining",
    filename: "DSC_6886.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "29",
    folder: "dining",
    filename: "DSC_7382.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "30",
    folder: "dining",
    filename: "DSC_5895.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "31",
    folder: "dining",
    filename: "DSC_6052.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "32",
    folder: "dining",
    filename: "DSC_6626.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "33",
    folder: "dining",
    filename: "DSC_6900.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "34",
    folder: "dining",
    filename: "DSC_7391.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "35",
    folder: "dining",
    filename: "DSC_5898.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "36",
    folder: "dining",
    filename: "DSC_6055.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "37",
    folder: "dining",
    filename: "DSC_6655.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "38",
    folder: "dining",
    filename: "DSC_6907.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "39",
    folder: "dining",
    filename: "DSC_7393.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "40",
    folder: "dining",
    filename: "DSC_5899.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "41",
    folder: "dining",
    filename: "DSC_6097.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "42",
    folder: "dining",
    filename: "DSC_6667.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "43",
    folder: "dining",
    filename: "DSC_7007.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "44",
    folder: "dining",
    filename: "DSC_7398.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "45",
    folder: "dining",
    filename: "DSC_5901.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "46",
    folder: "dining",
    filename: "DSC_6101.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "47",
    folder: "dining",
    filename: "DSC_6669.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "48",
    folder: "dining",
    filename: "DSC_7022.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "49",
    folder: "dining",
    filename: "DSC_7406.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "50",
    folder: "dining",
    filename: "DSC_5902.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "51",
    folder: "dining",
    filename: "DSC_6105.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "52",
    folder: "dining",
    filename: "DSC_6671.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "53",
    folder: "dining",
    filename: "DSC_7023.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "54",
    folder: "dining",
    filename: "DSC_7410.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "55",
    folder: "dining",
    filename: "DSC_5905.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "56",
    folder: "dining",
    filename: "DSC_6107.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "57",
    folder: "dining",
    filename: "DSC_6675.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "58",
    folder: "dining",
    filename: "DSC_7024.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "59",
    folder: "dining",
    filename: "DSC_7414.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "60",
    folder: "dining",
    filename: "DSC_5907.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "61",
    folder: "dining",
    filename: "DSC_6131.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "62",
    folder: "dining",
    filename: "DSC_6691.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "63",
    folder: "dining",
    filename: "DSC_7027.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "64",
    folder: "dining",
    filename: "DSC_7416.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "65",
    folder: "dining",
    filename: "DSC_5908.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "66",
    folder: "dining",
    filename: "DSC_6507.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "67",
    folder: "dining",
    filename: "DSC_6700.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "68",
    folder: "dining",
    filename: "DSC_7036.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "69",
    folder: "dining",
    filename: "DSC_7419.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "70",
    folder: "dining",
    filename: "DSC_5909.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "71",
    folder: "dining",
    filename: "DSC_6510.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "72",
    folder: "dining",
    filename: "DSC_6725.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "73",
    folder: "dining",
    filename: "DSC_7040.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "74",
    folder: "dining",
    filename: "DSC_7421.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "75",
    folder: "dining",
    filename: "DSC_5914.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "76",
    folder: "dining",
    filename: "DSC_6512.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "77",
    folder: "dining",
    filename: "DSC_6742.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "78",
    folder: "dining",
    filename: "DSC_7056.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "79",
    folder: "dining",
    filename: "DSC_7426.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "80",
    folder: "dining",
    filename: "DSC_5915.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "81",
    folder: "dining",
    filename: "DSC_6514.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "82",
    folder: "dining",
    filename: "DSC_6744.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "83",
    folder: "dining",
    filename: "DSC_7061.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "84",
    folder: "dining",
    filename: "DSC_7432.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "85",
    folder: "dining",
    filename: "DSC_5917.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "86",
    folder: "dining",
    filename: "DSC_6518.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "87",
    folder: "dining",
    filename: "DSC_6748.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "88",
    folder: "dining",
    filename: "DSC_7063.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "89",
    folder: "dining",
    filename: "DSC_7436.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "90",
    folder: "dining",
    filename: "DSC_5920.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "91",
    folder: "dining",
    filename: "DSC_6520.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "92",
    folder: "dining",
    filename: "DSC_6763.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "93",
    folder: "dining",
    filename: "DSC_7066.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "94",
    folder: "dining",
    filename: "DSC_7446.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "95",
    folder: "dining",
    filename: "DSC_5922.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "96",
    folder: "dining",
    filename: "DSC_6521.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "97",
    folder: "dining",
    filename: "DSC_6765.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "98",
    folder: "dining",
    filename: "DSC_7069.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "99",
    folder: "dining",
    filename: "DSC_7448.jpg",
    altText: "Dining image",
    isFavorite: false,
  },
  {
    id: "162",
    folder: "interior",
    filename: "DSC_7128.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "163",
    folder: "interior",
    filename: "DSC_7276.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "164",
    folder: "interior",
    filename: "DSC_7522.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "165",
    folder: "interior",
    filename: "DSC_7134.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "166",
    folder: "interior",
    filename: "DSC_7281.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "167",
    folder: "interior",
    filename: "DSC_7526.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "168",
    folder: "interior",
    filename: "DSC_7141.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "169",
    folder: "interior",
    filename: "DSC_7286.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "170",
    folder: "interior",
    filename: "DSC_7527.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "171",
    folder: "interior",
    filename: "DSC_7145.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "172",
    folder: "interior",
    filename: "DSC_7291.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "173",
    folder: "interior",
    filename: "DSC_7529.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "174",
    folder: "interior",
    filename: "DSC_7146.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "175",
    folder: "interior",
    filename: "DSC_7296.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "176",
    folder: "interior",
    filename: "DSC_7530.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "177",
    folder: "interior",
    filename: "DSC_7156.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "178",
    folder: "interior",
    filename: "DSC_7299.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "179",
    folder: "interior",
    filename: "DSC_7533.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "180",
    folder: "interior",
    filename: "DSC_7165.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "181",
    folder: "interior",
    filename: "DSC_7303.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "182",
    folder: "interior",
    filename: "DSC_7535.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "183",
    folder: "interior",
    filename: "DSC_7166.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "184",
    folder: "interior",
    filename: "DSC_7306.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "185",
    folder: "interior",
    filename: "DSC_7536.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "186",
    folder: "interior",
    filename: "DSC_7168.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "187",
    folder: "interior",
    filename: "DSC_7538.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "188",
    folder: "interior",
    filename: "DSC_7181.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "189",
    folder: "interior",
    filename: "DSC_7326.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "190",
    folder: "interior",
    filename: "DSC_7539.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "191",
    folder: "interior",
    filename: "DSC_7210.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "192",
    folder: "interior",
    filename: "DSC_7540.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "193",
    folder: "interior",
    filename: "DSC_7215.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "194",
    folder: "interior",
    filename: "DSC_7342.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "195",
    folder: "interior",
    filename: "DSC_7541.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "196",
    folder: "interior",
    filename: "DSC_7218.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "197",
    folder: "interior",
    filename: "DSC_7377.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "198",
    folder: "interior",
    filename: "DSC_7542.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "199",
    folder: "interior",
    filename: "DSC_7221.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "200",
    folder: "interior",
    filename: "DSC_7507.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "201",
    folder: "interior",
    filename: "DSC_7543.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "202",
    folder: "interior",
    filename: "DSC_7224.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "203",
    folder: "interior",
    filename: "DSC_7511.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "204",
    folder: "interior",
    filename: "DSC_7263.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "205",
    folder: "interior",
    filename: "DSC_7515.jpg",
    altText: "Image of interior",
    isFavorite: false,
  },
  {
    id: "206",
    folder: "aerials",
    filename: "DJI_0024.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "207",
    folder: "aerials",
    filename: "DJI_0270.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "208",
    folder: "aerials",
    filename: "DJI_0561.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "209",
    folder: "aerials",
    filename: "DJI_0026.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "210",
    folder: "aerials",
    filename: "DJI_0271.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "211",
    folder: "aerials",
    filename: "DJI_0567.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "212",
    folder: "aerials",
    filename: "DJI_0030.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "213",
    folder: "aerials",
    filename: "DJI_0272.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "214",
    folder: "aerials",
    filename: "DJI_0571.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "215",
    folder: "aerials",
    filename: "DJI_0036.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "216",
    folder: "aerials",
    filename: "DJI_0273.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "217",
    folder: "aerials",
    filename: "DJI_0572.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "218",
    folder: "aerials",
    filename: "DJI_0061.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "219",
    folder: "aerials",
    filename: "DJI_0274.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "220",
    folder: "aerials",
    filename: "DJI_0588.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "221",
    folder: "aerials",
    filename: "DJI_0081.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "222",
    folder: "aerials",
    filename: "DJI_0275.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "223",
    folder: "aerials",
    filename: "DJI_0592.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "224",
    folder: "aerials",
    filename: "DJI_0088.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "225",
    folder: "aerials",
    filename: "DJI_0276.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "226",
    folder: "aerials",
    filename: "DJI_0594.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "227",
    folder: "aerials",
    filename: "DJI_0105.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "228",
    folder: "aerials",
    filename: "DJI_0277.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "229",
    folder: "aerials",
    filename: "DJI_0613.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "230",
    folder: "aerials",
    filename: "DJI_0106.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "231",
    folder: "aerials",
    filename: "DJI_0281.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "232",
    folder: "aerials",
    filename: "DJI_0632.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "233",
    folder: "aerials",
    filename: "DJI_0110.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "234",
    folder: "aerials",
    filename: "DJI_0284.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "235",
    folder: "aerials",
    filename: "DJI_0634.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "236",
    folder: "aerials",
    filename: "DJI_0114.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "237",
    folder: "aerials",
    filename: "DJI_0287.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "238",
    folder: "aerials",
    filename: "DJI_0637.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "239",
    folder: "aerials",
    filename: "DJI_0125.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "240",
    folder: "aerials",
    filename: "DJI_0288.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "241",
    folder: "aerials",
    filename: "DJI_0663.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "242",
    folder: "aerials",
    filename: "DJI_0128.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "243",
    folder: "aerials",
    filename: "DJI_0294.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "244",
    folder: "aerials",
    filename: "DJI_0713.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "245",
    folder: "aerials",
    filename: "DJI_0138.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "246",
    folder: "aerials",
    filename: "DJI_0295.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "247",
    folder: "aerials",
    filename: "DJI_0141.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "248",
    folder: "aerials",
    filename: "DJI_0296.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "249",
    folder: "aerials",
    filename: "DJI_0769.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "250",
    folder: "aerials",
    filename: "DJI_0143.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "251",
    folder: "aerials",
    filename: "DJI_0297.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "252",
    folder: "aerials",
    filename: "DJI_0770.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "253",
    folder: "aerials",
    filename: "DJI_0155.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "254",
    folder: "aerials",
    filename: "DJI_0301.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "255",
    folder: "aerials",
    filename: "DJI_0773.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "256",
    folder: "aerials",
    filename: "DJI_0156.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "257",
    folder: "aerials",
    filename: "DJI_0302.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "258",
    folder: "aerials",
    filename: "DJI_0775.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "259",
    folder: "aerials",
    filename: "DJI_0157.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "260",
    folder: "aerials",
    filename: "DJI_0305.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "261",
    folder: "aerials",
    filename: "DJI_0777.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "262",
    folder: "aerials",
    filename: "DJI_0159.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "263",
    folder: "aerials",
    filename: "DJI_0541.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "264",
    folder: "aerials",
    filename: "DJI_0779.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "265",
    folder: "aerials",
    filename: "DJI_0161.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "266",
    folder: "aerials",
    filename: "DJI_0544.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "267",
    folder: "aerials",
    filename: "DJI_0781.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "268",
    folder: "aerials",
    filename: "DJI_0255.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "269",
    folder: "aerials",
    filename: "DJI_0547.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "270",
    folder: "aerials",
    filename: "DJI_0782.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "271",
    folder: "aerials",
    filename: "DJI_0256.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "272",
    folder: "aerials",
    filename: "DJI_0549.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "273",
    folder: "aerials",
    filename: "DJI_0783.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "274",
    folder: "aerials",
    filename: "DJI_0260.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "275",
    folder: "aerials",
    filename: "DJI_0550.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "276",
    folder: "aerials",
    filename: "DJI_0784.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "277",
    folder: "aerials",
    filename: "DJI_0261.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "278",
    folder: "aerials",
    filename: "DJI_0552.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "279",
    folder: "aerials",
    filename: "DJI_0786.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "280",
    folder: "aerials",
    filename: "DJI_0264.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "281",
    folder: "aerials",
    filename: "DJI_0553.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "282",
    folder: "aerials",
    filename: "DJI_0787.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "283",
    folder: "aerials",
    filename: "DJI_0265.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "284",
    folder: "aerials",
    filename: "DJI_0555.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "285",
    folder: "aerials",
    filename: "DJI_0799.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "286",
    folder: "aerials",
    filename: "DJI_0266.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "287",
    folder: "aerials",
    filename: "DJI_0556.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "288",
    folder: "aerials",
    filename: "DJI_0800.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "289",
    folder: "aerials",
    filename: "DJI_0267.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "290",
    folder: "aerials",
    filename: "DJI_0557.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "291",
    folder: "aerials",
    filename: "DJI_0801.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "292",
    folder: "aerials",
    filename: "DJI_0269.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "293",
    folder: "aerials",
    filename: "DJI_0559.jpg",
    altText: "Aerial image of boat",
    isFavorite: false,
  },
  {
    id: "294",
    folder: "entertainment",
    filename: "DSC_6159.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "295",
    folder: "entertainment",
    filename: "DSC_6309.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "296",
    folder: "entertainment",
    filename: "DSC_6368.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "297",
    folder: "entertainment",
    filename: "DSC_6434.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "298",
    folder: "entertainment",
    filename: "NIK_9605.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "299",
    folder: "entertainment",
    filename: "DSC_6264.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "300",
    folder: "entertainment",
    filename: "DSC_6320.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "301",
    folder: "entertainment",
    filename: "DSC_6371.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "302",
    folder: "entertainment",
    filename: "DSC_6438.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "303",
    folder: "entertainment",
    filename: "NIK_9621.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "304",
    folder: "entertainment",
    filename: "DSC_6267.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "305",
    folder: "entertainment",
    filename: "DSC_6325.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "306",
    folder: "entertainment",
    filename: "DSC_6402.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "307",
    folder: "entertainment",
    filename: "NIK_9584.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "308",
    folder: "entertainment",
    filename: "DSC_6285.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "309",
    folder: "entertainment",
    filename: "DSC_6327.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "310",
    folder: "entertainment",
    filename: "DSC_6410.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "311",
    folder: "entertainment",
    filename: "NIK_9589.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "312",
    folder: "entertainment",
    filename: "DSC_6294.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "313",
    folder: "entertainment",
    filename: "DSC_6332.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "314",
    folder: "entertainment",
    filename: "DSC_6416.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
  {
    id: "315",
    folder: "entertainment",
    filename: "NIK_9592.jpg",
    altText: "Activity image",
    isFavorite: false,
  },
];
